name: Train and Test

on:
  workflow_dispatch:

jobs:
  train_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Train model
        run: python src/training/train_model.py

      - name: Evaluate model
        run: python src/testing/evaluate.py

      - name: Run tests
        run: pytest tests/
